version: "3.7"

services:
  ruby_dev:
    build: .
    container_name: ruby_container
    ports:
      - "3000:3000"
    volumes:
      - ./:/opt/app

#docker-compose build
#docker-compose run --rm --service-ports ruby_dev